<?php

namespace AppBundle\Repository;

/**
 * TeplotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeplotaRepository extends \Doctrine\ORM\EntityRepository
{
}
